version: "3.9"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - path: ./database.env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytecrypt_api:
    build:
      context: .
    ports:
      - 5150:5150
    env_file:
      - path: ./database.env
        required: true
      - path: ./bytecrypt_api.env
        required: true
    develop:
      watch:
        - action: sync+restart
          path: ./bytecrypt_api
          target: /bytecrypt_api
    depends_on:
      - db

volumes:
  postgres_data:
