version: "3.9"

services:
  db:
    image: postgres:15-alpine3.18
    env_file:
      - path: ./database.env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    env_file:
      - path: ./database.env
        required: true
      - path: ./bytecrypt_api.env
        required: true
    ports:
      - 5150:5150
    volumes:
      - .:/bytecrypt_api
    tty: true
    stdin_open: true
    command: ["sh"]
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080

volumes:
  postgres_data:
