// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Administrator struct {
	ID       string
	Email    string
	Name     string
	Username string
	Password string
	Role     int32
}

type Role struct {
	ID    int32
	Title string
}

type Subscription struct {
	ID    int64
	Email string
	Name  string
}
